[project]
name = "app"
version = "0.1.0"
description = "A Jac project"
authors = []
license = "MIT"
entry-point = "main.jac"

[dependencies]

[dev-dependencies]

[run]
main = true
cache = true

[build]
typecheck = false

[test]
verbose = false
fail_fast = false

[serve]
port = 8000

[cache]
enabled = true
dir = ".jac_cache"

[scripts]
dev = "jac run main.jac"
build = "jac build main.jac --typecheck"
test = "jac test"

[plugins.scale]
kubernetes.app_name = "todo"
kubernetes.namespace = "todo-app"
kubernetes.node_port = 30051